### ISSUE TITLE
Error 525: Review your SSL certificate 

### ISSUE THREAD

**Issue by ralflorent** [soundhive/front#115]
Hi there!
I wanted to have a look at your website (https://soundhive.stream/) and realized that you're facing an SSL-certificate issue. Therefore, your website is unavailable (see the attachment).

Hopefully, you can have a look at it soon!

**Comment by angristan** [comment]
👋 This was a school project, the website is not available anymore 😅

**Comment by ralflorent** [comment]
Oh sorry. I was unaware.
